fix tester issue
RostyslavToch/TransIT.Client pull request #177
Opened 2019-05-27 10:08 UTC by markiyanshvets

2019-06-01 18:31 UTC, danylo-dudok requested changes

2019-06-01 18:31 UTC, danylo-dudok commented on src/app/modules/shared/components/supplier/edit-supplier/edit-supplier.component.ts
> +      if(element.id== form.currency){
===

2019-06-01 18:31 UTC, danylo-dudok commented on src/app/modules/shared/components/supplier/edit-supplier/edit-supplier.component.ts
> +      if(element.id== form.currency){
element.id === parseInt(form.currency)

2019-06-02 21:37 UTC, markiyanshvets commented on src/app/modules/shared/components/supplier/edit-supplier/edit-supplier.component.ts
> +      if(element.id== form.currency){
okay

2019-06-02 21:50 UTC, TarasKvasnytsya approved these changes

2019-06-02 21:50 UTC, TarasKvasnytsya commented on src/app/modules/shared/components/supplier/edit-supplier/edit-supplier.component.ts
> +    this.countries.forEach(element => {
currentCountry = this.countries[this.countries.findIndex(element => element.id === parseInt(form.country))];

2019-06-02 21:50 UTC, TarasKvasnytsya commented on src/app/modules/shared/components/supplier/edit-supplier/edit-supplier.component.ts
> +    this.countries.forEach(element => {
I think it will be better then cycle and if operator

2019-06-03 10:46 UTC, danylo-dudok approved these changes

2019-06-03 10:46 UTC, danylo-dudok commented on src/app/modules/shared/components/supplier/edit-supplier/edit-supplier.component.ts
> +    this.currencies.forEach(element => {
Array.filter

2019-06-03 10:50 UTC, merged