Engineer role
RostyslavToch/TransIT.Client pull request #39
Opened 2019-04-20 11:48 UTC by danylo-dudok

I have done 2 simple table for issues & issue-logs, fixed models and restructure their location. Editing and adding issue-log is comming soon.

2019-04-20 21:57 UTC, CrazyRoka requested changes

2019-04-20 21:57 UTC, RostyslavToch commented on package.json
> +    "datatables.net-select-dt": "^1.3.0",
Do we need it? It can be included in index.html

2019-04-20 21:57 UTC, RostyslavToch commented on src/app/modules/engineer/engineer.module.ts
> +    IssueLogsComponent
Do it need export?

2019-04-22 16:15 UTC, CrazyRoka approved these changes

2019-04-22 17:10 UTC, IrynaPanchuk97 approved these changes

2019-04-23 17:04 UTC, merged