20-user-view
RostyslavToch/TransIT.Client pull request #40
Opened 2019-04-20 19:35 UTC by IrynaPanchuk97

2019-04-20 21:53 UTC, CrazyRoka requested changes

2019-04-20 21:53 UTC, RostyslavToch commented on package.json
> +    "jquery": "^3.4.0",
Delete it

2019-04-21 08:04 UTC, IrynaPanchuk97 commented on package.json
> +    "jquery": "^3.4.0",
done

2019-04-21 10:44 UTC, CrazyRoka approved these changes

2019-04-21 19:52 UTC, yuriimochulskyi approved these changes

2019-04-22 09:06 UTC, merged