Refactor folder
RostyslavToch/TransIT.Client pull request #78
Opened 2019-04-30 17:19 UTC by IrynaPanchuk97

2019-05-01 12:11 UTC, danylo-dudok approved these changes

2019-05-01 13:28 UTC, CrazyRoka requested changes

2019-05-01 13:28 UTC, RostyslavToch commented on src/app/custom-errors.ts
> +export function MatchPasswordFormat(label: string, error: any): string {
camelCase

2019-05-01 13:28 UTC, RostyslavToch commented on src/app/custom-errors.ts
> +  if (password != confirmPassword) {
!==

2019-05-01 13:29 UTC, RostyslavToch commented on src/app/custom-errors.ts
> +  if (password != confirmPassword) {
camelCase in functuin name

2019-05-02 12:20 UTC, CrazyRoka approved these changes

2019-05-02 12:24 UTC, merged